#!/usr/bin/env python3
"""Batch-audit a list of skills defined in a YAML config.

Reads config with `sources:` containing GitHub raw URLs / local file paths,
runs each through audit_skill.py logic, writes one report per skill, then
prints a leaderboard.

Usage:
    python3 batch_audit.py --config config/skills_to_audit.yaml --output reports/
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import yaml
from datetime import datetime
from pathlib import Path

# Reuse audit_skill helpers
HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))

from audit_skill import (  # noqa: E402
    fetch_url,
    parse_frontmatter,
    extract_skill_body,
    summarize_skill_heuristic,
    summarize_skill_llm,
    call_audit_endpoint,
    format_report_markdown,
    DEFAULT_ENGINE_URL,
)


def process_source(
    source_label: str,
    skill_text: str,
    source_url: str | None,
    engine_url: str,
    out_dir: Path,
    domain: str,
    use_llm_summary: bool,
) -> dict | None:
    """Audit one skill, write report. Returns a leaderboard entry or None on failure."""
    frontmatter = parse_frontmatter(skill_text)
    skill_name = (frontmatter.get("name") or "unnamed-skill").strip()

    result = call_audit_endpoint(engine_url, skill_text, domain=domain)
    if not result.get("success", True) and "error" in result:
        print(f"  ✗ audit failed for {skill_name}: {result['error']}", file=sys.stderr)
        return None

    body = extract_skill_body(skill_text)
    body_metrics = {"body_lines": body.count("\n"), "body_chars": len(body)}

    llm_summary = None
    if use_llm_summary:
        llm_summary = summarize_skill_llm(
            skill_text=skill_text,
            frontmatter=frontmatter,
            api_key=os.environ.get("OPENAI_API_KEY"),
            base_url=os.environ.get("OPENAI_BASE_URL"),
            model=os.environ.get("OPENAI_MODEL"),
        )
    heuristic = summarize_skill_heuristic(skill_text, frontmatter)
    skill_summary = (
        f"_Auditor's read (LLM-generated):_ {llm_summary}\n\n{heuristic}"
        if llm_summary else heuristic
    )

    report_md = format_report_markdown(
        skill_name=skill_name,
        source_url=source_url,
        frontmatter=frontmatter,
        skill_summary=skill_summary,
        audit_result=result,
        body_metrics=body_metrics,
    )
    safe_name = re.sub(r"[^A-Za-z0-9_-]", "_", skill_name)
    out_path = out_dir / f"{safe_name}-{datetime.utcnow().strftime('%Y%m%d')}.md"
    out_path.write_text(report_md, encoding="utf-8")

    score = result.get("score", 0)
    grade = result.get("grade", "?")
    sev_counts = result.get("severity_counts", {})
    print(f"  ✓ {skill_name}: {grade} ({score}/100) "
          f"[crit={sev_counts.get('critical', 0)} high={sev_counts.get('high', 0)} "
          f"warn={sev_counts.get('warning', 0)}] → {out_path.name}", file=sys.stderr)
    return {
        "source": source_label,
        "name": skill_name,
        "score": score,
        "grade": grade,
        "sev_counts": sev_counts,
        "report_path": str(out_path),
        "source_url": source_url,
    }


def write_leaderboard(results: list[dict], out_dir: Path, edition: str) -> Path:
    """Write a leaderboard markdown indexing all per-skill reports."""
    ranked = sorted(results, key=lambda r: r["score"], reverse=True)
    md = []
    md.append(f"# TAR Engine 米其林指南 — {edition}")
    md.append("")
    md.append(f"_{len(results)} skills audited · "
              f"generated {datetime.utcnow().strftime('%Y-%m-%d')}_")
    md.append("")
    md.append("Each report below is generated by [TAR Engine](https://github.com/qingxuantang/tar-engine) "
              "static audit pipeline. Reports cite line-level evidence, "
              "per-category sub-scores, full rule registry, and remediation hints "
              "per finding. The scoring rubric is uniform across all skills.")
    md.append("")
    md.append("## Leaderboard")
    md.append("")
    md.append("| Rank | Grade | Score | Skill | Findings | Source |")
    md.append("|:---:|:---:|---:|---|---|---|")
    badges = {"A": "🟢 A", "B": "🟢 B", "C": "🟡 C", "D": "🟠 D", "F": "🔴 F"}
    for i, r in enumerate(ranked, 1):
        sev = r["sev_counts"]
        findings_str_parts = []
        if sev.get("critical"):
            findings_str_parts.append(f"🔴×{sev['critical']}")
        if sev.get("high"):
            findings_str_parts.append(f"🟠×{sev['high']}")
        if sev.get("warning"):
            findings_str_parts.append(f"🟡×{sev['warning']}")
        findings_str = " ".join(findings_str_parts) or "—"
        report_filename = Path(r["report_path"]).name
        skill_cell = f"[`{r['name']}`]({report_filename})"
        src_cell = r["source"]
        if r.get("source_url"):
            src_cell = f"[{src_cell}]({r['source_url']})"
        md.append(f"| {i} | {badges.get(r['grade'], r['grade'])} | "
                  f"{r['score']} | {skill_cell} | {findings_str} | {src_cell} |")
    md.append("")
    md.append("## Methodology")
    md.append("")
    md.append("All reports were generated by the same TAR Engine static audit "
              "pipeline using rule set v1.0.0 (17 universal rules + per-domain "
              "extensions). Skills are sorted by score, ties broken by name.")
    md.append("")
    md.append("Want your skill in next week's audit? "
              "Open an issue on [github.com/qingxuantang/tar-engine](https://github.com/qingxuantang/tar-engine/issues).")
    md.append("")

    leaderboard_path = out_dir / f"leaderboard-{edition.replace(' ', '-').lower()}.md"
    leaderboard_path.write_text("\n".join(md), encoding="utf-8")
    return leaderboard_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="YAML config file")
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--engine-url", default=DEFAULT_ENGINE_URL)
    parser.add_argument("--domain", default="general")
    parser.add_argument("--edition", default=None,
                        help="Edition label (e.g. '2026-W23'); defaults to today's ISO week")
    parser.add_argument("--no-llm-summary", action="store_true",
                        help="Skip LLM-powered skill summary (faster, no BYOK needed)")
    args = parser.parse_args()

    config = yaml.safe_load(Path(args.config).read_text(encoding="utf-8")) or {}
    sources = config.get("sources", [])
    if not sources:
        print("No sources in config.", file=sys.stderr)
        return 1

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    edition = args.edition or datetime.utcnow().strftime("Edition %Y-W%V")

    print(f"Processing {len(sources)} source group(s) → {out_dir}", file=sys.stderr)
    results: list[dict] = []
    for src in sources:
        name = src.get("name", "?")
        urls = src.get("urls", []) or []
        files = src.get("files", []) or []
        print(f"\n[{name}]", file=sys.stderr)

        for url in urls:
            try:
                text = fetch_url(url)
            except Exception as e:
                print(f"  ✗ fetch failed {url}: {e}", file=sys.stderr)
                continue
            r = process_source(name, text, url, args.engine_url, out_dir,
                               args.domain, use_llm_summary=not args.no_llm_summary)
            if r:
                results.append(r)

        for fp in files:
            try:
                text = Path(fp).read_text(encoding="utf-8")
            except Exception as e:
                print(f"  ✗ read failed {fp}: {e}", file=sys.stderr)
                continue
            r = process_source(name, text, None, args.engine_url, out_dir,
                               args.domain, use_llm_summary=not args.no_llm_summary)
            if r:
                results.append(r)

    print(f"\nDone. {len(results)} skills audited.", file=sys.stderr)
    if results:
        avg = sum(r["score"] for r in results) / len(results)
        print(f"Average score: {avg:.1f}/100", file=sys.stderr)
        leaderboard_path = write_leaderboard(results, out_dir, edition)
        print(f"\nLeaderboard: {leaderboard_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
