#!/usr/bin/env python3
"""Build a single self-contained HTML page for one 米其林指南 edition.

Takes the directory of markdown reports produced by `batch_audit.py` and
emits one HTML file with:
- Hero section with edition label + summary stats
- Leaderboard table (linked anchor per skill)
- Collapsible per-skill sections with the full report inlined

The HTML is self-contained: marked.js loaded from CDN (jsdelivr), all
styles inline. Drop the file behind nginx and it just works.

Usage:
    python3 build_site.py \
        --input /tmp/audit-michelin-w23 \
        --output /var/www/michelin/2026-W23.html \
        --edition "2026-W23"
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from datetime import datetime
from pathlib import Path


SUPPORTED_LANGS = ("en", "zh")
DEFAULT_LANG = "en"


# ── HTML chrome localization ──────────────────────────────────────
SITE_STRINGS = {
    "en": {
        "html_lang": "en",
        "page_title": "TAR Engine Skill Audit Guide · {edition}",
        "page_description": "Static audit reports for Claude Code skills, generated by TAR Engine. Edition {edition} · {n} skills audited.",
        "eyebrow": "TAR Engine · Skill Audit Report",
        "title": "Skill Audit Guide · {edition}",
        "subtitle": "Static security &amp; quality audit of {n} Claude Code skills, generated by TAR Engine's L1 rule set.",
        "meta_generated": "Generated",
        "meta_engine": "Engine",
        "stat_skills": "Skills audited",
        "stat_avg": "Average score",
        "stat_a_passes": "Grade A passes",
        "stat_findings": "Total findings",
        "sec_leaderboard": "Leaderboard",
        "th": ["#", "Grade", "Score", "Skill", "Findings"],
        "sec_full_reports": "Full reports",
        "full_reports_intro": "Click any skill to expand the full audit report with line-level evidence, per-category breakdown, methodology, and the complete rule registry that was applied.",
        "click_to_expand": "— click to read full report",
        "no_findings": "no findings",
        "footer_a": "Each report cites a specific commit of the TAR Engine static rule set. The methodology, rule IDs, and remediation hints are part of every report — nothing about the scoring is hidden.",
        "footer_b": 'Want your skill audited in a future edition? Open an issue at <a href="https://github.com/qingxuantang/tar-engine/issues">github.com/qingxuantang/tar-engine</a>.',
        "footer_copy": "© {year} · TAR Engine Skill Audit Guide · Generated {ts}",
    },
    "zh": {
        "html_lang": "zh-CN",
        "page_title": "TAR Engine 技能审计指南 · {edition}",
        "page_description": "TAR Engine 自动生成的 Claude Code skill 静态审计报告。{edition} · 共审计 {n} 个 skill。",
        "eyebrow": "TAR Engine · 技能审计报告",
        "title": "技能审计指南 · {edition}",
        "subtitle": "由 TAR Engine L1 规则集对 {n} 个 Claude Code skill 进行静态安全与质量审计。",
        "meta_generated": "生成于",
        "meta_engine": "Engine",
        "stat_skills": "审计 skill 数",
        "stat_avg": "平均分",
        "stat_a_passes": "A 级通过数",
        "stat_findings": "命中总数",
        "sec_leaderboard": "排行榜",
        "th": ["#", "等级", "得分", "Skill", "命中"],
        "sec_full_reports": "完整报告",
        "full_reports_intro": "点击任一 skill 展开完整审计报告：含命中行号 + 上下文 / 按类别分项 / 方法学 / 完整规则 registry。",
        "click_to_expand": "— 点击查看完整报告",
        "no_findings": "无 finding",
        "footer_a": "每篇报告都明确引用 TAR Engine 静态规则集的某个 commit。方法学、rule ID、修复建议都内嵌在报告里——评分不藏私。",
        "footer_b": '想让你的 skill 出现在下一期？在 <a href="https://github.com/qingxuantang/tar-engine/issues">github.com/qingxuantang/tar-engine</a> 开 issue。',
        "footer_copy": "© {year} · TAR Engine 技能审计指南 · 生成于 {ts}",
    },
}


def s(key: str, lang: str, **fmt) -> str:
    bundle = SITE_STRINGS.get(lang) or SITE_STRINGS[DEFAULT_LANG]
    val = bundle.get(key) or SITE_STRINGS[DEFAULT_LANG].get(key, key)
    return val.format(**fmt) if fmt else val


# ── Inline CSS — publication style, mobile-first ──────────────────────
CSS = """
:root {
  --bg: #0a0e14;
  --bg-card: #131820;
  --bg-card-alt: #1a2030;
  --text: #e6edf3;
  --text-dim: #8b97a8;
  --text-quiet: #5a6478;
  --accent: #5eba7d;
  --accent-dim: #3a8c5b;
  --warn: #d9a64a;
  --danger: #d94a4a;
  --border: #1e2630;
  --link: #6cb9f0;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter",
               "Segoe UI", "PingFang SC", system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  font-size: 16px;
  -webkit-font-smoothing: antialiased;
}
.wrap {
  max-width: 920px;
  margin: 0 auto;
  padding: 32px 24px 64px;
}
.lang-toggle {
  position: fixed;
  top: 14px;
  right: 14px;
  display: flex;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 999px;
  padding: 3px;
  z-index: 50;
  box-shadow: 0 4px 12px rgba(0,0,0,0.3);
}
.lang-toggle a {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-dim);
  text-decoration: none;
  padding: 5px 12px;
  border-radius: 999px;
  transition: background 0.1s, color 0.1s;
  letter-spacing: 0.02em;
}
.lang-toggle a:hover { color: var(--text); }
.lang-toggle a.active {
  background: var(--accent-dim);
  color: var(--bg);
}
@media (max-width: 480px) {
  .lang-toggle { top: 10px; right: 10px; }
  .lang-toggle a { font-size: 11px; padding: 4px 10px; }
}
header.hero {
  border-bottom: 1px solid var(--border);
  padding-bottom: 28px;
  margin-bottom: 36px;
}
.eyebrow {
  font-size: 12px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--accent);
  font-weight: 600;
  margin: 0 0 12px 0;
}
h1.title {
  font-size: 34px;
  font-weight: 700;
  letter-spacing: -0.01em;
  margin: 0 0 8px 0;
  line-height: 1.2;
}
.subtitle {
  color: var(--text-dim);
  font-size: 16px;
  margin: 0 0 18px 0;
}
.meta {
  font-size: 13px;
  color: var(--text-quiet);
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
}
.meta strong { color: var(--text-dim); font-weight: 600; }
.stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px;
  margin: 24px 0 0 0;
}
.stat {
  background: var(--bg-card);
  border: 1px solid var(--border);
  padding: 14px 16px;
  border-radius: 8px;
}
.stat-label {
  font-size: 11px;
  letter-spacing: 0.08em;
  color: var(--text-quiet);
  text-transform: uppercase;
  margin: 0 0 6px 0;
}
.stat-value {
  font-size: 22px;
  font-weight: 700;
  color: var(--text);
}
.stat-value.accent { color: var(--accent); }
h2.section-title {
  font-size: 22px;
  font-weight: 700;
  margin: 48px 0 16px 0;
  padding-top: 8px;
}
.leaderboard {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 10px;
  overflow: hidden;
  margin-bottom: 36px;
}
.leaderboard table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
}
.leaderboard th {
  text-align: left;
  background: var(--bg-card-alt);
  color: var(--text-dim);
  font-weight: 600;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  padding: 12px 14px;
  border-bottom: 1px solid var(--border);
}
.leaderboard td {
  padding: 14px;
  border-bottom: 1px solid var(--border);
  vertical-align: middle;
}
.leaderboard tr:last-child td { border-bottom: none; }
.leaderboard tr:hover td { background: var(--bg-card-alt); }
.rank { color: var(--text-quiet); font-variant-numeric: tabular-nums; }
.grade-badge {
  display: inline-block;
  font-weight: 700;
  padding: 3px 8px;
  border-radius: 4px;
  font-size: 13px;
  font-variant-numeric: tabular-nums;
}
.grade-A { background: rgba(94, 186, 125, 0.15); color: var(--accent); }
.grade-B { background: rgba(94, 186, 125, 0.10); color: var(--accent-dim); }
.grade-C { background: rgba(217, 166, 74, 0.18); color: var(--warn); }
.grade-D { background: rgba(217, 74, 74, 0.15); color: var(--danger); }
.grade-F { background: rgba(217, 74, 74, 0.22); color: var(--danger); }
.score { font-variant-numeric: tabular-nums; color: var(--text-dim); }
.skill-link { color: var(--link); text-decoration: none; font-weight: 600; }
.skill-link:hover { text-decoration: underline; }
.findings-pill {
  display: inline-block;
  font-size: 12px;
  font-variant-numeric: tabular-nums;
  background: var(--bg-card-alt);
  padding: 2px 7px;
  border-radius: 12px;
  color: var(--text-dim);
}
.findings-pill.crit { color: var(--danger); }
.findings-pill.high { color: var(--warn); }
.findings-clean { color: var(--text-quiet); font-size: 13px; }

details.report-section {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 10px;
  margin-bottom: 18px;
  overflow: hidden;
  transition: border-color 0.15s;
}
details.report-section[open] {
  border-color: var(--accent-dim);
}
details.report-section summary {
  cursor: pointer;
  padding: 16px 20px;
  list-style: none;
  display: flex;
  align-items: center;
  gap: 12px;
  user-select: none;
  background: var(--bg-card);
  font-weight: 600;
  font-size: 15px;
  transition: background 0.1s;
}
details.report-section summary:hover {
  background: var(--bg-card-alt);
}
details.report-section summary::-webkit-details-marker { display: none; }
details.report-section summary::after {
  content: "▾";
  margin-left: auto;
  color: var(--text-quiet);
  transition: transform 0.15s;
}
details.report-section[open] summary::after { transform: rotate(180deg); }
.summary-meta {
  margin-left: 8px;
  font-size: 13px;
  font-weight: 400;
  color: var(--text-dim);
}
.report-body {
  padding: 16px 24px 28px;
  border-top: 1px solid var(--border);
  background: var(--bg);
}
.report-body h1 { display: none; } /* report's own h1 redundant with summary */
.report-body h2 {
  font-size: 17px;
  margin: 28px 0 10px;
  padding-bottom: 6px;
  border-bottom: 1px solid var(--border);
  color: var(--text);
}
.report-body h3 { font-size: 15px; margin: 22px 0 8px; }
.report-body p { margin: 8px 0; }
.report-body ul, .report-body ol { padding-left: 22px; }
.report-body li { margin: 4px 0; }
.report-body code {
  font-family: ui-monospace, "SF Mono", "Cascadia Code", Menlo, monospace;
  background: var(--bg-card-alt);
  padding: 1px 6px;
  border-radius: 3px;
  font-size: 0.92em;
  color: var(--text);
}
.report-body pre {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 12px 14px;
  overflow-x: auto;
  font-size: 13px;
}
.report-body pre code {
  background: transparent;
  padding: 0;
  font-size: 13px;
}
.report-body table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
  margin: 12px 0;
}
.report-body th, .report-body td {
  text-align: left;
  padding: 8px 10px;
  border-bottom: 1px solid var(--border);
}
.report-body th {
  background: var(--bg-card-alt);
  color: var(--text-dim);
  font-weight: 600;
  text-transform: uppercase;
  font-size: 11px;
  letter-spacing: 0.04em;
}
.report-body blockquote {
  border-left: 3px solid var(--accent-dim);
  margin: 12px 0;
  padding: 4px 14px;
  color: var(--text-dim);
  background: var(--bg-card);
  border-radius: 0 4px 4px 0;
}
.report-body details summary {
  cursor: pointer;
  color: var(--link);
  font-size: 13px;
  padding: 6px 0;
}
.report-body a { color: var(--link); }

footer {
  margin-top: 60px;
  padding-top: 24px;
  border-top: 1px solid var(--border);
  font-size: 13px;
  color: var(--text-quiet);
  text-align: center;
}
footer a { color: var(--link); }

@media (max-width: 600px) {
  .wrap { padding: 20px 14px 48px; }
  h1.title { font-size: 26px; }
  .leaderboard td, .leaderboard th { padding: 10px; font-size: 13px; }
  .report-body { padding: 12px 16px 20px; }
}
"""


def grade_class(grade: str) -> str:
    return f"grade-{grade}" if grade in "ABCDF" else "grade-A"


def render_findings_pill(sev_counts: dict) -> str:
    crit = sev_counts.get("critical", 0)
    high = sev_counts.get("high", 0)
    warn = sev_counts.get("warning", 0)
    parts = []
    if crit:
        parts.append(f'<span class="findings-pill crit">🔴 {crit}</span>')
    if high:
        parts.append(f'<span class="findings-pill high">🟠 {high}</span>')
    if warn:
        parts.append(f'<span class="findings-pill">🟡 {warn}</span>')
    if not parts:
        return '<span class="findings-clean">no findings</span>'
    return " ".join(parts)


def parse_leaderboard_md(md_path: Path) -> list[dict]:
    """Pull leaderboard rows from the markdown leaderboard.

    Expected format: `| 1 | 🟢 A | 100 | [`name`](file.md) | findings | source |`
    The leaderboard table is the FIRST 6-column markdown table in the file
    (language-agnostic — we don't depend on the column header text).
    """
    rows: list[dict] = []
    if not md_path.exists():
        return rows
    text = md_path.read_text(encoding="utf-8")

    in_table = False
    seen_header = False
    for line in text.splitlines():
        stripped = line.strip()
        # Markdown table separator row (e.g. `|:---:|:---:|---:|---|---|---|`)
        is_sep = bool(re.match(r"^[\|\s:\-]+$", stripped)) and stripped.count("|") >= 6
        is_table_row = stripped.startswith("|") and stripped.count("|") >= 7
        if is_sep:
            # Once we see a separator we know the previous line was the header.
            in_table = True
            seen_header = True
            continue
        if not is_table_row:
            if in_table:
                in_table = False
                seen_header = False
            continue
        if not seen_header:
            # First |...| row before separator is the header; skip it.
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if len(cells) < 6:
            continue
        rank_s, grade_s, score_s, skill_s, findings_s, source_s = cells[:6]
        name_match = re.search(r"\[`([^`]+)`\]\(([^)]+)\)", skill_s)
        if not name_match:
            continue
        skill_name = name_match.group(1)
        report_file = name_match.group(2)
        grade_letter = grade_s.strip().split()[-1]
        rows.append({
            "rank": int(rank_s) if rank_s.isdigit() else 0,
            "grade": grade_letter,
            "score": int(score_s) if score_s.isdigit() else 0,
            "skill_name": skill_name,
            "report_file": report_file,
            "findings_md": findings_s,
            "source_md": source_s,
        })
    return rows


def load_report_md(report_file: Path) -> str:
    """Read a per-skill report markdown, return raw text."""
    return report_file.read_text(encoding="utf-8")


def render_skill_section(row: dict, md_text: str, lang: str = DEFAULT_LANG) -> str:
    """One <details> per skill, body rendered via marked.js client-side."""
    safe_id = re.sub(r"[^a-z0-9_-]", "-", row["skill_name"].lower())
    grade_cls = grade_class(row["grade"])
    expand_hint = s("click_to_expand", lang)
    return f"""
<details class="report-section" id="skill-{safe_id}">
  <summary>
    <span class="rank">#{row['rank']}</span>
    <span class="grade-badge {grade_cls}">{row['grade']}</span>
    <span class="score">{row['score']}/100</span>
    <code>{html.escape(row['skill_name'])}</code>
    <span class="summary-meta">{expand_hint}</span>
  </summary>
  <div class="report-body" data-md="{safe_id}"></div>
  <script type="text/markdown" id="md-{safe_id}">{html.escape(md_text)}</script>
</details>"""


def build_html(edition: str, leaderboard_rows: list[dict],
               input_dir: Path, generated_at: str, lang: str = DEFAULT_LANG) -> str:
    n = len(leaderboard_rows)
    avg_score = round(sum(r["score"] for r in leaderboard_rows) / n, 1) if n else 0
    a_count = sum(1 for r in leaderboard_rows if r["grade"] == "A")
    issues_total = sum(
        sum(int(x) for x in re.findall(r"×(\d+)", r["findings_md"]))
        for r in leaderboard_rows
    )

    # Render leaderboard table
    lb_rows_html = []
    for r in leaderboard_rows:
        safe_id = re.sub(r"[^a-z0-9_-]", "-", r["skill_name"].lower())
        grade_cls = grade_class(r["grade"])
        lb_rows_html.append(f"""
        <tr>
          <td class="rank">{r['rank']}</td>
          <td><span class="grade-badge {grade_cls}">{r['grade']}</span></td>
          <td class="score">{r['score']}</td>
          <td><a class="skill-link" href="#skill-{safe_id}">{html.escape(r['skill_name'])}</a></td>
          <td>{render_findings_pill_from_md(r['findings_md'], lang)}</td>
        </tr>""")

    # Render per-skill sections
    section_html_parts = []
    for r in leaderboard_rows:
        report_path = input_dir / r["report_file"]
        if not report_path.exists():
            print(f"warn: report missing for {r['skill_name']}: {report_path}",
                  file=sys.stderr)
            continue
        md = load_report_md(report_path)
        section_html_parts.append(render_skill_section(r, md, lang))

    th = SITE_STRINGS[lang]["th"]
    th_html = "".join(f"<th>{h}</th>" for h in th)

    return f"""<!DOCTYPE html>
<html lang="{s('html_lang', lang)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
<meta name="theme-color" content="#0a0e14">
<title>{html.escape(s('page_title', lang, edition=edition))}</title>
<meta name="description" content="{html.escape(s('page_description', lang, edition=edition, n=n))}">
<style>{CSS}</style>
</head>
<body data-lang="{lang}">

<nav class="lang-toggle" aria-label="Language">
  <a href="#" data-lang-switch="en" class="{'active' if lang == 'en' else ''}">EN</a>
  <a href="#" data-lang-switch="zh" class="{'active' if lang == 'zh' else ''}">中</a>
</nav>

<div class="wrap">

<header class="hero">
  <p class="eyebrow">{s('eyebrow', lang)}</p>
  <h1 class="title">{html.escape(s('title', lang, edition=edition))}</h1>
  <p class="subtitle">{s('subtitle', lang, n=n)}</p>
  <div class="meta">
    <span><strong>{s('meta_generated', lang)}:</strong> {html.escape(generated_at)}</span>
    <span><strong>{s('meta_engine', lang)}:</strong> <a href="https://github.com/qingxuantang/tar-engine">tar-engine OSS</a></span>
  </div>
  <div class="stats">
    <div class="stat">
      <p class="stat-label">{s('stat_skills', lang)}</p>
      <p class="stat-value">{n}</p>
    </div>
    <div class="stat">
      <p class="stat-label">{s('stat_avg', lang)}</p>
      <p class="stat-value accent">{avg_score}/100</p>
    </div>
    <div class="stat">
      <p class="stat-label">{s('stat_a_passes', lang)}</p>
      <p class="stat-value">{a_count} / {n}</p>
    </div>
    <div class="stat">
      <p class="stat-label">{s('stat_findings', lang)}</p>
      <p class="stat-value">{issues_total}</p>
    </div>
  </div>
</header>

<h2 class="section-title">{s('sec_leaderboard', lang)}</h2>
<div class="leaderboard">
<table>
<thead>
<tr>{th_html}</tr>
</thead>
<tbody>
{"".join(lb_rows_html)}
</tbody>
</table>
</div>

<h2 class="section-title">{s('sec_full_reports', lang)}</h2>
<p style="color: var(--text-dim); margin-top: -8px;">{s('full_reports_intro', lang)}</p>

{"".join(section_html_parts)}

<footer>
  <p>{s('footer_a', lang)}</p>
  <p>{s('footer_b', lang)}</p>
  <p style="margin-top: 18px; font-size: 11px;">{s('footer_copy', lang, year=datetime.utcnow().year, ts=html.escape(generated_at))}</p>
</footer>

</div>

<!-- Render the embedded markdown reports client-side -->
<script src="https://cdn.jsdelivr.net/npm/marked@12.0.0/marked.min.js"></script>
<script>
(function() {{
  if (typeof marked === 'undefined') {{
    console.warn('marked.js failed to load; reports stay as raw markdown');
    return;
  }}
  marked.setOptions({{ breaks: false, gfm: true }});
  document.querySelectorAll('.report-body[data-md]').forEach(function(el) {{
    var id = 'md-' + el.dataset.md;
    var src = document.getElementById(id);
    if (!src) return;
    var raw = src.textContent;
    el.innerHTML = marked.parse(raw);
  }});
}})();
</script>

<!-- Language toggle behavior -->
<script>
(function() {{
  var currentLang = document.body.dataset.lang || 'en';

  // Persist preference in cookie (nginx checks this on /michelin/ redirects)
  function setLangCookie(lang) {{
    var maxAge = 60 * 60 * 24 * 365;  // 1 year
    document.cookie = 'michelin_lang=' + lang +
      '; path=/michelin/; max-age=' + maxAge + '; SameSite=Lax';
    try {{ localStorage.setItem('michelin_lang', lang); }} catch (_) {{}}
  }}

  // Compute the equivalent URL in the target language for the current page.
  function siblingUrl(targetLang) {{
    var path = window.location.pathname;
    // Pattern A: /michelin/<edition>-en.html or -zh.html
    var m = path.match(/^(.*)-(?:en|zh)(\.html)$/);
    if (m) return m[1] + '-' + targetLang + m[2] + window.location.hash;
    // Pattern B: anything else under /michelin/ (e.g. /michelin/ or /michelin/latest.html)
    if (path.indexOf('/michelin/') === 0) {{
      return '/michelin/latest-' + targetLang + '.html' + window.location.hash;
    }}
    // Fallback: append ?lang=
    var sep = path.indexOf('?') === -1 ? '?' : '&';
    return path + sep + 'lang=' + targetLang;
  }}

  document.querySelectorAll('.lang-toggle a[data-lang-switch]').forEach(function(btn) {{
    btn.addEventListener('click', function(ev) {{
      ev.preventDefault();
      var target = btn.dataset.langSwitch;
      if (!target || target === currentLang) return;
      setLangCookie(target);
      window.location.assign(siblingUrl(target));
    }});
  }});

  // Record current language as a baseline preference so a subsequent visit to
  // /michelin/ uses it. Don't overwrite an existing explicit preference.
  if (!/(?:^|;\s*)michelin_lang=/.test(document.cookie)) {{
    setLangCookie(currentLang);
  }}
}})();
</script>

</body>
</html>"""


def render_findings_pill_from_md(findings_md: str, lang: str = DEFAULT_LANG) -> str:
    """The leaderboard markdown encodes findings as `🔴×3 🟠×1 🟡×2` or `—`."""
    findings_md = findings_md.strip()
    no_findings_html = f'<span class="findings-clean">{s("no_findings", lang)}</span>'
    if not findings_md or findings_md == "—":
        return no_findings_html
    parts = []
    if m := re.search(r"🔴×(\d+)", findings_md):
        parts.append(f'<span class="findings-pill crit">🔴 {m.group(1)}</span>')
    if m := re.search(r"🟠×(\d+)", findings_md):
        parts.append(f'<span class="findings-pill high">🟠 {m.group(1)}</span>')
    if m := re.search(r"🟡×(\d+)", findings_md):
        parts.append(f'<span class="findings-pill">🟡 {m.group(1)}</span>')
    return " ".join(parts) or no_findings_html


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True,
                        help="Directory of per-skill *.md + leaderboard-*.md")
    parser.add_argument("--output", required=True, help="Output HTML file path")
    parser.add_argument("--edition", required=True,
                        help='Edition label, e.g. "2026-W23"')
    parser.add_argument("--lang", default=DEFAULT_LANG, choices=SUPPORTED_LANGS,
                        help=f"Chrome language (default: {DEFAULT_LANG})")
    args = parser.parse_args()

    input_dir = Path(args.input)
    if not input_dir.is_dir():
        print(f"input directory not found: {input_dir}", file=sys.stderr)
        return 1

    # Find leaderboard markdown — pick the matching edition or the only one
    lb_candidates = list(input_dir.glob(f"leaderboard-*{args.edition.lower()}*.md"))
    if not lb_candidates:
        lb_candidates = list(input_dir.glob("leaderboard-*.md"))
    if not lb_candidates:
        print(f"no leaderboard markdown in {input_dir}", file=sys.stderr)
        return 1
    leaderboard_md = lb_candidates[0]
    rows = parse_leaderboard_md(leaderboard_md)
    if not rows:
        print(f"could not parse rows from {leaderboard_md}", file=sys.stderr)
        return 1

    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    html_out = build_html(args.edition, rows, input_dir, generated_at, lang=args.lang)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html_out, encoding="utf-8")
    print(f"✅ {len(rows)} skills → {out_path} ({out_path.stat().st_size} bytes)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
