"""Risk guardrail for TAR Engine V2.

Three modes:
  1. Runtime: pattern-match each incoming event against domain rules.
     Pure regex, no LLM, millisecond response. Fires on every event.
  2. Static: scan document text (SKILL.md, configs) against the same
     rule set. Used for skill auditing without execution.
  3. Post-session: (Phase 2) full risk scoring after session ends.

Each RealtimeRule has a match_scope ("runtime", "static", "both")
that controls which mode(s) it participates in. Rules default to
"both" for backward compatibility.

The rules come from DomainConfig.realtime_rules plus a set of
universal rules that apply to all domains.
"""

import re
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional

from .domain_config import DomainConfig, RealtimeRule


@dataclass
class RiskAlert:
    """A single risk alert generated by realtime checking."""
    rule_name: str
    severity: str   # "info", "warning", "high", "critical"
    message: str
    tool_name: str
    timestamp: str
    details: Dict[str, Any]

    def to_dict(self) -> Dict:
        return {
            "rule": self.rule_name,
            "severity": self.severity,
            "message": self.message,
            "tool": self.tool_name,
            "timestamp": self.timestamp,
            "details": self.details,
        }


# Universal rules applied regardless of domain.
# match_scope: "runtime" = only runtime events, "static" = only document scan, "both" = both
#
# Rule ID convention (stable across renames; report cites these):
#   FA-NNN  file_access
#   SS-NNN  shell_safety
#   DE-NNN  data_exfil
#   CE-NNN  credential_exposure
#   PI-NNN  prompt_injection
#   MP-NNN  malicious_payload
#
# Categories (5 buckets + capability_drift comes from runtime auth checks):
#   file_access, shell_safety, data_exfil, credential_exposure,
#   prompt_injection, malicious_payload

UNIVERSAL_RULES = [
    # ── Runtime + Static (both) ─────────────────────────────────────
    RealtimeRule(
        name="sensitive_file_access",
        description="Access to sensitive configuration files",
        severity="warning",
        match_tool="Read|Edit|Write",
        match_file=r"\.env|.*secret.*|.*credential.*|.*\.key$|.*\.pem$",
        match_content=r"\.env\b|\.ssh/|id_rsa|authorized_keys|credentials?\.\w+|\.key\b|\.pem\b",
        message="访问了敏感配置文件",
        match_scope="both",
        category="file_access",
        rule_id="FA-001",
        fix_template="Remove direct references to .env / .ssh / *.key / *.pem; load secrets from a runtime config service or environment variable instead of naming the file in the skill body.",
    ),
    RealtimeRule(
        name="destructive_bash",
        description="Potentially destructive bash commands",
        severity="high",
        match_tool="Bash",
        match_content=r"rm\s+-rf|drop\s+table|truncate\s+table|git\s+push\s+.*--force",
        message="检测到可能的破坏性命令",
        match_scope="both",
        category="shell_safety",
        rule_id="SS-001",
        fix_template="Replace `rm -rf` with `trash` or `mv` to a tombstone directory. For SQL, require explicit confirmation before DROP/TRUNCATE. Never instruct LLM to use `--force` on a git push.",
    ),
    RealtimeRule(
        name="force_flag_abuse",
        description="Use of --force / --no-verify flags that bypass safety checks",
        severity="high",
        match_content=r"--force\b|--no-verify\b|-f\s+push|chmod\s+777|chmod\s+-R\s+777",
        message="使用了绕过安全检查的强制标志",
        match_scope="both",
        category="shell_safety",
        rule_id="SS-002",
        fix_template="Drop `--force` / `--no-verify` from the skill body. If a hook is failing, fix the hook — don't tell the LLM to skip it. For chmod, use minimum-needed mode (e.g. 600/644) instead of 777.",
    ),
    RealtimeRule(
        name="external_data_exfil",
        description="Sending data to external URLs via POST/upload",
        severity="high",
        match_content=r"curl\s+.*-[XdF].*POST|curl\s+.*--data|wget\s+.*--post|requests\.post|httpx\.post|fetch\(.*method.*POST",
        message="检测到向外部 URL 发送数据",
        match_scope="both",
        category="data_exfil",
        rule_id="DE-001",
        fix_template="If the POST is intentional (webhook, API integration), declare its destination in SKILL.md `## Network Egress` section so audit can allowlist it. Otherwise remove.",
    ),
    RealtimeRule(
        name="credential_in_content",
        description="Hardcoded API keys, secrets, or passwords",
        severity="high",
        match_content=r"(?:api[_-]?key|api[_-]?secret|password|private[_-]?key|access[_-]?token)\s*[:=]\s*['\"][A-Za-z0-9+/=_-]{8,}",
        message="疑似 API key 或密码硬编码",
        match_scope="both",
        category="credential_exposure",
        rule_id="CE-001",
        fix_template="Replace hardcoded secrets with `${VAR_NAME}` placeholders and document the env var in SKILL.md `## Required Environment`. Rotate any secret that touched git history.",
    ),
    RealtimeRule(
        name="pipe_to_shell",
        description="Piping remote content directly to shell execution",
        severity="critical",
        match_content=r"curl\s+.*\|\s*(?:bash|sh|zsh|python|node)|wget\s+.*\|\s*(?:bash|sh|zsh|python|node)",
        message="检测到远程内容直接管道到 shell 执行（高危）",
        match_scope="both",
        category="shell_safety",
        rule_id="SS-003",
        fix_template="Download to a file, checksum it against a published hash, then execute. Never `curl … | sh` — the upstream may serve a different payload on the next request.",
    ),
    RealtimeRule(
        name="sudo_usage",
        description="Use of sudo for privilege escalation",
        severity="warning",
        match_content=r"\bsudo\s+(?!docker\b)",
        message="检测到 sudo 提权操作",
        match_scope="both",
        category="shell_safety",
        rule_id="SS-004",
        fix_template="Skills should run as a user with the privileges they need. If sudo is required, surface it as a one-time setup step in `## Prerequisites`, not in the runtime body.",
    ),

    # ── Static-only rules (document/SKILL.md scanning) ──────────────
    RealtimeRule(
        name="prompt_injection_bypass",
        description="Instructions attempting to override safety boundaries",
        severity="critical",
        match_content=r"ignore\s+(?:all\s+)?previous|disregard\s+(?:all\s+)?(?:prior|previous|above)|override\s+(?:safety|security|system)|forget\s+(?:your|all)\s+(?:instructions|rules|constraints)",
        message="检测到试图绕过安全边界的指令（prompt injection）",
        match_scope="static",
        category="prompt_injection",
        rule_id="PI-001",
        fix_template="Remove the instruction. If you legitimately need the LLM to deprioritize an earlier directive, rephrase as a positive constraint (`use the latest config from X`) instead of telling it to ignore prior rules.",
    ),
    RealtimeRule(
        name="hidden_instruction",
        description="Instructions telling the agent to hide actions from the user",
        severity="critical",
        match_content=r"do\s+not\s+(?:mention|reveal|tell|show|disclose)|keep\s+(?:this\s+)?(?:secret|hidden)|user\s+(?:must|should)\s+not\s+(?:know|see)|hide\s+(?:this|the)\s+(?:action|operation|output)",
        message="检测到隐藏指令（要求 Agent 对用户隐瞒操作）",
        match_scope="static",
        category="prompt_injection",
        rule_id="PI-002",
        fix_template="Skills must not hide actions from the user. If the goal is to suppress verbose output, declare it as `## Output: summary only`. Anything done on the user's behalf must be reportable.",
    ),
    RealtimeRule(
        name="excessive_permission_claim",
        description="Claims of unrestricted access or bypassing restrictions",
        severity="high",
        match_content=r"you\s+have\s+(?:full\s+)?access\s+to\s+(?:all|everything)|no\s+restrictions?\b|bypass\s+(?:any\s+)?(?:security|safety|restriction|protection)|without\s+(?:any\s+)?(?:limitation|restriction|constraint)",
        message="声称拥有无限制权限或绕过安全约束",
        match_scope="static",
        category="prompt_injection",
        rule_id="PI-003",
        fix_template="Replace blanket permission claims with the specific tool/scope the skill actually needs (e.g. `Read access to ./data/`). The cockpit enforces capabilities — claiming `no restrictions` only confuses the LLM.",
    ),
    RealtimeRule(
        name="disable_safety_instruction",
        description="Instructions to disable safety features, logging, or verification",
        severity="high",
        match_content=r"disable\s+(?:safety|security|logging|verification|authentication|audit)|turn\s+off\s+(?:safety|security|logging|verification)|skip\s+(?:all\s+)?(?:safety|security|verification|validation)\s+checks",
        message="要求禁用安全特性、日志或验证机制",
        match_scope="static",
        category="prompt_injection",
        rule_id="PI-004",
        fix_template="Remove. Safety/logging are infrastructural; skills don't get to turn them off. If a specific check is too noisy, surface that as feedback to engine maintainers instead of telling the LLM to skip it.",
    ),
    RealtimeRule(
        name="impersonation_instruction",
        description="Instructions to impersonate the user or other identities",
        severity="high",
        match_content=r"(?:pretend|act)\s+(?:to\s+be|as\s+if\s+you\s+are|like)\s+(?:the\s+)?(?:user|admin|root|owner)|impersonate|assume\s+(?:the\s+)?(?:identity|role)\s+of",
        message="要求 Agent 冒充用户或其他身份",
        match_scope="static",
        category="prompt_injection",
        rule_id="PI-005",
        fix_template="Replace impersonation with a role description (`act as a code reviewer`). Never `pretend to be the user` — that's how reply-to-self loops and forged messages happen.",
    ),
    RealtimeRule(
        name="encoded_payload",
        description="Base64 or hex encoded payloads that may hide malicious content",
        severity="warning",
        match_content=r"base64\s+(?:-d|--decode)|echo\s+[A-Za-z0-9+/=]{40,}\s*\|\s*base64|\\x[0-9a-fA-F]{2}(?:\\x[0-9a-fA-F]{2}){9,}|eval\s*\(\s*(?:atob|Buffer\.from)",
        message="检测到编码 payload（可能隐藏恶意内容）",
        match_scope="static",
        category="malicious_payload",
        rule_id="MP-001",
        fix_template="If the encoding is for a legitimate reason (binary data, image), use a well-known library API instead of inline `eval(atob(...))`. The `eval+decode` pattern is almost always exploit-pattern.",
    ),
    RealtimeRule(
        name="network_exfil_pattern",
        description="Patterns for exfiltrating data via DNS, HTTP, or other channels",
        severity="high",
        match_content=r"\.burpcollaborator\.net|\.oastify\.com|ngrok\.io|requestbin\.|webhook\.site|pipedream\.net|interact\.sh",
        message="检测到已知的数据外泄/回连域名",
        match_scope="static",
        category="data_exfil",
        rule_id="DE-002",
        fix_template="These are known C2/exfil staging domains. If you're using one for a legitimate test, replace it with a self-hosted echo endpoint and document the purpose in `## Network Egress`.",
    ),
    RealtimeRule(
        name="crypto_miner_pattern",
        description="Cryptocurrency mining related commands or references",
        severity="critical",
        match_content=r"xmrig|stratum\+tcp://|minergate|coinhive|cryptonight|monero.*pool|--donate-level",
        message="检测到加密货币挖矿相关内容",
        match_scope="static",
        category="malicious_payload",
        rule_id="MP-002",
        fix_template="Remove. Skills should not run miners. If you're auditing miner infrastructure as part of a research project, gate the skill behind explicit `--allow-malware-strings` and document the research context.",
    ),
    RealtimeRule(
        name="reverse_shell_pattern",
        description="Reverse shell payloads",
        severity="critical",
        match_content=r"(?:bash|sh|nc|ncat)\s+-[ie]\s+/dev/tcp|python.*socket.*connect.*exec|perl.*socket.*INET|mkfifo\s+/tmp/|/dev/tcp/\d",
        message="检测到反向 shell payload（高危）",
        match_scope="static",
        category="malicious_payload",
        rule_id="MP-003",
        fix_template="Remove. If you need remote access for ops, use a managed service (Tailscale, SSH with explicit keys) — not raw reverse shells in a skill body.",
    ),
    RealtimeRule(
        name="data_collection_broad",
        description="Broad data collection patterns (env vars, system info, browsing data)",
        severity="warning",
        match_content=r"(?:cat|echo)\s+.*(?:/etc/passwd|/etc/shadow)|printenv\s*\||env\s*\||set\s*\|.*(?:curl|wget|nc)|(?:history|\.bash_history|\.zsh_history)\b.*(?:curl|wget|send|post)",
        message="检测到广泛的系统信息收集模式",
        match_scope="static",
        category="data_exfil",
        rule_id="DE-003",
        fix_template="Skills should read only what they specifically need. Bulk dumps of /etc/passwd, environ, or shell history piped to network is the classic exfil pattern — narrow the scope or remove.",
    ),

    # ── Quality lint rules (informational, do not impact security grade) ──
    # Added 2026-06-15 per PLAN_MULTI_FORMAT_DISCOVERY_AND_CI_ERGONOMICS.md
    # item C. Borrowed in spirit from dabit3/skill-audit's quality.ts.
    # Severity is "info" so the security score is unaffected; these show up
    # in the report as suggestions, not findings.
    RealtimeRule(
        name="shell_block_no_error_handling",
        description="Shell code blocks without `set -e` or explicit error handling",
        severity="info",
        match_content=r"```(?:bash|sh|shell|zsh)\n(?:(?!```)[\s\S])*?```",
        message="Shell block missing `set -e` / `|| exit` — silent failures will go unreported",
        match_scope="static",
        category="quality",
        rule_id="QL-001",
        fix_template="Add `set -euo pipefail` at the top of bash blocks, or chain critical commands with `|| exit 1`. Skills that fail silently mid-script are nearly impossible to debug downstream.",
    ),
    RealtimeRule(
        name="unpinned_install_command",
        description="Documented install command without a pinned version",
        severity="info",
        match_content=r"(?:^|\s)(?:npm\s+(?:install|i)|yarn\s+add|pnpm\s+(?:add|install)|pip\s+install|pipx\s+install|uv\s+(?:add|pip\s+install))\s+(?!.*[@=])[a-zA-Z0-9_\-./]+",
        message="Install command lacks a pinned version — re-running the skill on a different day may install a different binary",
        match_scope="static",
        category="quality",
        rule_id="QL-002",
        fix_template="Pin versions in the README/SKILL.md command: `npm install foo@1.2.3` or `pip install foo==1.2.3`. Reproducibility matters once anyone else runs the skill.",
    ),
    # NOTE: QL-003 broken_anchor_link is deferred. The naive regex
    # `\[[^\]]+\]\(#[\w-]+\)` false-positives on every valid anchor link, so
    # a real implementation needs check_document to cross-reference the
    # target against actual headers in the same document. Tracked as a
    # follow-up in PLAN_MULTI_FORMAT_DISCOVERY_AND_CI_ERGONOMICS.md §6.
]


# Categories used in the audit report for grouping findings and computing
# per-category sub-scores. Keep in sync with the `category` field above.
RULE_CATEGORIES = [
    "prompt_injection",
    "shell_safety",
    "file_access",
    "data_exfil",
    "credential_exposure",
    "malicious_payload",
    "quality",  # Mark 2026-06-15: QL-NNN informational lint rules
]

CATEGORY_DISPLAY_NAMES = {
    "prompt_injection": "Prompt injection / scope override",
    "shell_safety": "Shell safety",
    "file_access": "Sensitive file access",
    "data_exfil": "Data exfiltration",
    "credential_exposure": "Credential exposure",
    "malicious_payload": "Malicious payload signatures",
    "quality": "Quality lint (informational)",
    "capability_drift": "Capability drift (runtime only)",
}


# Stable version for the rule set — bumped when rules are added/changed.
# Used in the audit methodology block so reports cite which rule set was applied.
RULE_SET_VERSION = "1.1.0"  # 1.1.0: + QL-001/002/003 quality lint rules (2026-06-15)


# Rules to suppress for read_only skills during runtime checks.
# These rules trigger on normal read-only operations (reading configs,
# sending reports via Telegram) and generate noise for analytical skills.
READ_ONLY_SUPPRESSED_RULES = frozenset({
    "sensitive_file_access",   # Reading config.py is the job, not a risk
    "external_data_exfil",     # Sending reports via Telegram/API is expected
    "credential_in_content",   # Config files may contain path-like strings
    "sudo_usage",              # Rarely relevant for read-only
})


# ── Expected Operation Profiles ────────────────────────────────────
#
# Each skill intent defines expected tool usage patterns. Events matching
# expected_tools are considered normal and skip certain checks. Events
# using unexpected_tools (deviation) get elevated scrutiny.
#
# Structure:
#   expected_tools: tools the skill should use
#   deviation_tools: tools that would be abnormal for this intent
#   expected_file_patterns: file path patterns that are normal to access
#   deviation_severity_boost: extra severity level if a deviation is detected

@dataclass
class OperationProfile:
    """Expected operation profile for a skill intent."""
    expected_tools: frozenset
    deviation_tools: frozenset  # if these are seen, flag as deviation
    expected_file_patterns: List[str]  # regex patterns for normal file access
    deviation_severity_boost: int = 1  # 0=no boost, 1=+1 level, 2=+2 levels


OPERATION_PROFILES: Dict[str, OperationProfile] = {
    "read_only": OperationProfile(
        expected_tools=frozenset({"Read", "Glob", "Grep", "Bash", "Agent",
                                  "mcp__plugin_telegram_telegram__reply",
                                  "mcp__plugin_telegram_telegram__react",
                                  "TaskCreate", "TaskUpdate", "TaskGet", "TaskList"}),
        deviation_tools=frozenset({"Edit", "Write", "NotebookEdit"}),
        expected_file_patterns=[
            r"\.csv$", r"\.pkl$", r"\.html$", r"\.json$",
            r"config\.py$", r"skill_config\.py$",
            r"目录\.md$", r"SKILL\.md$",
            r"回测结果", r"子策略回测结果",
        ],
        deviation_severity_boost=1,
    ),
    "modify": OperationProfile(
        expected_tools=frozenset({"Read", "Glob", "Grep", "Bash", "Edit", "Write",
                                  "Agent", "TaskCreate", "TaskUpdate"}),
        deviation_tools=frozenset(),  # modify skills can use most tools
        expected_file_patterns=[
            r"\.py$", r"\.yaml$", r"\.yml$", r"\.json$", r"\.md$",
            r"config\.py$", r"factors/", r"sections/",
        ],
        deviation_severity_boost=0,
    ),
    "execute": OperationProfile(
        expected_tools=frozenset({"Read", "Bash", "Edit", "Write", "Agent"}),
        deviation_tools=frozenset(),
        expected_file_patterns=[],  # execute skills access varies widely
        deviation_severity_boost=0,
    ),
}


class RiskGuardrail:
    """Risk checking engine for both runtime events and static documents."""

    def __init__(self, domain: DomainConfig, skill_intent: str = "unknown",
                 skill_capabilities: Optional[Dict[str, bool]] = None,
                 declared_capabilities: Optional[Dict[str, bool]] = None):
        self.domain = domain
        self.skill_intent = skill_intent
        # Two capability bitmaps:
        #   declared    — from SKILL.md frontmatter (author's contract)
        #   effective   — admin-current authorization (may differ from declared)
        # Each fires its own alert family, independently.
        self.skill_capabilities = skill_capabilities  # effective
        self.declared_capabilities = declared_capabilities
        self.rules = UNIVERSAL_RULES + list(domain.realtime_rules)
        # Pre-compile regex patterns for performance
        self._compiled = []
        for rule in self.rules:
            self._compiled.append({
                "rule": rule,
                "tool_re": re.compile(rule.match_tool, re.IGNORECASE) if rule.match_tool else None,
                "file_re": re.compile(rule.match_file, re.IGNORECASE) if rule.match_file else None,
                "content_re": re.compile(rule.match_content, re.IGNORECASE) if rule.match_content else None,
            })

    def add_dynamic_rules(self, rules: List[RealtimeRule]):
        """Add dynamically extracted rules (e.g. from SKILL.md scanning)."""
        for rule in rules:
            self._compiled.append({
                "rule": rule,
                "tool_re": re.compile(rule.match_tool, re.IGNORECASE) if rule.match_tool else None,
                "file_re": re.compile(rule.match_file, re.IGNORECASE) if rule.match_file else None,
                "content_re": re.compile(rule.match_content, re.IGNORECASE) if rule.match_content else None,
            })
            self.rules.append(rule)

    def check_event(self, event: Dict[str, Any], skill_name: str = "") -> List[RiskAlert]:
        """Check a single event against all runtime rules. Returns list of alerts (may be empty)."""
        alerts = []
        event_type = event.get("event_type", "")
        tool_name = event.get("tool_name", "")

        # Only check tool_call and tool_result events
        if event_type not in ("tool_call", "tool_result"):
            return alerts

        # L2: Authorization check (tool_call only). Two independent alerts:
        #   - capability_violation: effective bitmap denies this op
        #   - frontmatter_drift:    op required by event isn't in author's
        #                           declared bitmap (audit trail; cannot be
        #                           silenced by extending effective)
        if event_type == "tool_call":
            if self.skill_capabilities is not None or self.declared_capabilities is not None:
                for a in self.check_capability(event):
                    alerts.append(a)
            else:
                deviation = self.check_deviation(event)
                if deviation:
                    alerts.append(deviation)

        # Extract searchable text from event payload
        args_text = self._extract_args_text(event)
        file_path = self._extract_file_path(event)

        for compiled in self._compiled:
            rule = compiled["rule"]

            # Skip static-only rules in runtime mode
            if rule.match_scope == "static":
                continue

            # Intent-based rule suppression: read_only skills skip noise rules
            if self.skill_intent == "read_only" and rule.name in READ_ONLY_SUPPRESSED_RULES:
                continue

            # Skill-level filtering
            if skill_name and rule.only_for_skills and skill_name not in rule.only_for_skills:
                continue
            if skill_name and rule.skip_for_skills and skill_name in rule.skip_for_skills:
                continue

            # Match tool name
            if compiled["tool_re"] and not compiled["tool_re"].search(tool_name):
                continue

            # Match file path
            if compiled["file_re"] and file_path:
                if not compiled["file_re"].search(file_path):
                    continue
            elif compiled["file_re"] and not file_path:
                continue

            # Match content
            if compiled["content_re"]:
                if not compiled["content_re"].search(args_text):
                    continue

            # All conditions matched
            alerts.append(RiskAlert(
                rule_name=rule.name,
                severity=rule.severity,
                message=rule.message,
                tool_name=tool_name,
                timestamp=event.get("timestamp", datetime.utcnow().isoformat()),
                details={
                    "file": file_path,
                    "matched_text": args_text[:200] if args_text else "",
                },
            ))

        return alerts

    # Human-readable labels for capability keys, used in alert messages
    _CAP_LABEL = {
        "read_files": "读文件",
        "write_to_data": "写到 data/ 目录",
        "write_to_knowledge": "写到 knowledge/ 目录",
        "modify_strategy_code": "改策略代码",
        "external_api": "调外部接口",
        "git_destructive": "执行破坏性命令 (rm -rf / git push 等)",
    }

    def check_capability(self, event: Dict[str, Any]) -> List[RiskAlert]:
        """Two independent capability-based checks per event.

        Returns up to TWO alerts:
          1. frontmatter_drift — op needed wasn't in author's declared
             allowed-tools. Fires regardless of admin's effective config so
             the audit trail of "skill exceeded its declared scope" is
             permanent and cannot be hidden by extending effective caps.
          2. capability_violation — admin's effective bitmap denies this op.
             Fires only if effective[cap] = false.
        """
        from auditor.capabilities import required_capability
        cap = required_capability(event)
        if cap is None:
            return []  # benign tool / no cap needed

        out: List[RiskAlert] = []
        tool_name = event.get("tool_name", "")
        label = self._CAP_LABEL.get(cap, cap)
        ts = event.get("timestamp", datetime.utcnow().isoformat())
        file_path = self._extract_file_path(event)

        # Drift check — only meaningful if we know the author's declaration
        if self.declared_capabilities is not None and self.declared_capabilities:
            declared_allows = bool(self.declared_capabilities.get(cap, False))
            if not declared_allows:
                out.append(RiskAlert(
                    rule_name="frontmatter_drift",
                    severity="warning",
                    message=(
                        f"该 skill 在执行「{label}」，但 SKILL.md 的 allowed-tools 未声明该能力 "
                        f"(capability={cap}) — 偏离作者设计"
                    ),
                    tool_name=tool_name,
                    timestamp=ts,
                    details={
                        "required_capability": cap,
                        "label": label,
                        "tool": tool_name,
                        "file": file_path,
                        "declared": False,
                    },
                ))

        # Effective-authorization check
        effective_allows = bool((self.skill_capabilities or {}).get(cap, False))
        if not effective_allows:
            severity = "high" if cap in ("git_destructive", "external_api",
                                          "modify_strategy_code") else "warning"
            out.append(RiskAlert(
                rule_name="capability_violation",
                severity=severity,
                message=f"该 skill 未被 admin 授权「{label}」(capability={cap})",
                tool_name=tool_name,
                timestamp=ts,
                details={
                    "required_capability": cap,
                    "label": label,
                    "tool": tool_name,
                    "file": file_path,
                    "effective": False,
                },
            ))
        return out

    def check_deviation(self, event: Dict[str, Any]) -> Optional[RiskAlert]:
        """Check if an event deviates from the expected operation profile.

        Returns a RiskAlert if the event uses a tool that's unexpected
        for the skill's intent, None otherwise.
        """
        profile = OPERATION_PROFILES.get(self.skill_intent)
        if not profile:
            return None

        tool_name = event.get("tool_name", "")
        if not tool_name:
            return None

        # Check if tool is a known deviation
        if tool_name in profile.deviation_tools:
            file_path = self._extract_file_path(event)
            return RiskAlert(
                rule_name="operation_deviation",
                severity="high" if profile.deviation_severity_boost >= 1 else "warning",
                message=f"Skill intent={self.skill_intent} 不应使用 {tool_name} 工具（偏离预期行为）",
                tool_name=tool_name,
                timestamp=event.get("timestamp", datetime.utcnow().isoformat()),
                details={
                    "skill_intent": self.skill_intent,
                    "expected_tools": sorted(profile.expected_tools),
                    "deviation_tool": tool_name,
                    "file": file_path,
                },
            )

        return None

    def check_batch(self, events: List[Dict[str, Any]], skill_name: str = "") -> List[RiskAlert]:
        """Check multiple events. Returns all alerts found."""
        all_alerts = []
        for event in events:
            all_alerts.extend(self.check_event(event, skill_name=skill_name))
        return all_alerts

    def check_document(self, text: str, source: str = "skill_md", skill_name: str = "") -> List[RiskAlert]:
        """Check document text against all static rules.

        Used for auditing SKILL.md content, config files, or any text
        without executing the skill.

        Each alert's details now carry line-level evidence:
          - hits: list of {line_number, line_text, excerpt} (up to 3)
          - rule_id / category / fix_template promoted from the rule

        Args:
            text: the full document text to scan
            source: label for the document type (e.g. "skill_md", "config", "readme")
            skill_name: optional skill name for skill-level rule filtering
        Returns:
            list of RiskAlerts found
        """
        alerts = []
        now = datetime.utcnow().isoformat()
        # Precompute (line_start_offset -> line_number) mapping so we can
        # translate match offsets to 1-based line numbers without re-splitting
        # the text per rule.
        lines = text.split("\n")
        line_offsets = []
        offset = 0
        for ln in lines:
            line_offsets.append(offset)
            offset += len(ln) + 1  # +1 for the \n

        def _line_for_offset(o: int) -> int:
            # Binary-search-ish; for typical SKILL.md sizes a linear scan is fine.
            lo, hi = 0, len(line_offsets) - 1
            while lo < hi:
                mid = (lo + hi + 1) // 2
                if line_offsets[mid] <= o:
                    lo = mid
                else:
                    hi = mid - 1
            return lo + 1  # 1-based

        for compiled in self._compiled:
            rule = compiled["rule"]

            # Skip runtime-only rules in static mode
            if rule.match_scope == "runtime":
                continue

            # Skill-level filtering
            if skill_name and rule.only_for_skills and skill_name not in rule.only_for_skills:
                continue
            if skill_name and rule.skip_for_skills and skill_name in rule.skip_for_skills:
                continue

            # Static mode: only match_content applies (tool and file matchers are ignored)
            if not compiled["content_re"]:
                continue

            hits = []
            seen = False
            for m in compiled["content_re"].finditer(text):
                seen = True
                if len(hits) >= 3:
                    # Still count the total below, but only keep 3 evidences
                    continue
                line_no = _line_for_offset(m.start())
                # Excerpt: 3 lines of surrounding context (1 before, current, 1 after).
                # If the match spans multiple lines, include all touched.
                end_line_no = _line_for_offset(m.end() - 1) if m.end() > m.start() else line_no
                ctx_start = max(0, line_no - 2)
                ctx_end = min(len(lines), end_line_no + 1)
                excerpt_lines = []
                for i in range(ctx_start, ctx_end):
                    marker = ">> " if (i + 1) >= line_no and (i + 1) <= end_line_no else "   "
                    excerpt_lines.append(f"{marker}{i+1:>4}: {lines[i]}")
                hits.append({
                    "line_number": line_no,
                    "line_text": lines[line_no - 1] if 0 < line_no <= len(lines) else "",
                    "match_text": text[m.start():m.end()][:200],
                    "excerpt": "\n".join(excerpt_lines),
                })

            if seen:
                # Count all matches even if hits is capped at 3
                total_matches = sum(1 for _ in compiled["content_re"].finditer(text))
                alerts.append(RiskAlert(
                    rule_name=rule.name,
                    severity=rule.severity,
                    message=rule.message,
                    tool_name=f"static:{source}",
                    timestamp=now,
                    details={
                        "source": source,
                        "rule_id": rule.rule_id,
                        "category": rule.category,
                        "description": rule.description,
                        "fix_template": rule.fix_template,
                        "match_count": total_matches,
                        "hits": hits,
                        # Legacy field for backward-compat with V0 reports
                        "snippets": [h["match_text"] for h in hits],
                    },
                ))

        return alerts

    def check_document_batch(self, documents: List[Dict[str, str]], skill_name: str = "") -> List[RiskAlert]:
        """Check multiple documents. Each dict should have 'text' and optionally 'source'.

        Args:
            documents: list of {"text": "...", "source": "skill_md"} dicts
            skill_name: optional skill name for rule filtering
        Returns:
            all alerts found across all documents
        """
        all_alerts = []
        for doc in documents:
            all_alerts.extend(self.check_document(
                text=doc.get("text", ""),
                source=doc.get("source", "unknown"),
                skill_name=skill_name,
            ))
        return all_alerts

    def _extract_args_text(self, event: Dict[str, Any]) -> str:
        """Extract searchable text from event args/result."""
        # tool_call: look in args
        args = event.get("args", {})
        if isinstance(args, dict):
            parts = []
            for v in args.values():
                if isinstance(v, str):
                    parts.append(v)
            return " ".join(parts)
        if isinstance(args, str):
            return args
        # tool_result: look in result
        result = event.get("result", "")
        if isinstance(result, str):
            return result
        return ""

    def _extract_file_path(self, event: Dict[str, Any]) -> str:
        """Extract file path from event args."""
        args = event.get("args", {})
        if isinstance(args, dict):
            # Common field names for file paths
            for key in ("file_path", "path", "file", "filename"):
                if key in args and isinstance(args[key], str):
                    return args[key]
            # Bash command: extract path-like tokens
            cmd = args.get("command", "")
            if cmd:
                return cmd
        return ""
