"""Risk guardrail for TAR Engine V2.

Three modes:
  1. Runtime: pattern-match each incoming event against domain rules.
     Pure regex, no LLM, millisecond response. Fires on every event.
  2. Static: scan document text (SKILL.md, configs) against the same
     rule set. Used for skill auditing without execution.
  3. Post-session: (Phase 2) full risk scoring after session ends.

Each RealtimeRule has a match_scope ("runtime", "static", "both")
that controls which mode(s) it participates in. Rules default to
"both" for backward compatibility.

The rules come from DomainConfig.realtime_rules plus a set of
universal rules that apply to all domains.
"""

import re
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional

from .domain_config import DomainConfig, RealtimeRule


@dataclass
class RiskAlert:
    """A single risk alert generated by realtime checking."""
    rule_name: str
    severity: str   # "info", "warning", "high", "critical"
    message: str
    tool_name: str
    timestamp: str
    details: Dict[str, Any]

    def to_dict(self) -> Dict:
        return {
            "rule": self.rule_name,
            "severity": self.severity,
            "message": self.message,
            "tool": self.tool_name,
            "timestamp": self.timestamp,
            "details": self.details,
        }


# Universal rules applied regardless of domain.
# match_scope: "runtime" = only runtime events, "static" = only document scan, "both" = both
UNIVERSAL_RULES = [
    # ── Runtime + Static (both) ─────────────────────────────────────
    RealtimeRule(
        name="sensitive_file_access",
        description="Access to sensitive configuration files",
        severity="warning",
        match_tool="Read|Edit|Write",
        match_file=r"\.env|.*secret.*|.*credential.*|.*\.key$|.*\.pem$",
        match_content=r"\.env\b|\.ssh/|id_rsa|authorized_keys|credentials?\.\w+|\.key\b|\.pem\b",
        message="访问了敏感配置文件",
        match_scope="both",
    ),
    RealtimeRule(
        name="destructive_bash",
        description="Potentially destructive bash commands",
        severity="high",
        match_tool="Bash",
        match_content=r"rm\s+-rf|drop\s+table|truncate\s+table|git\s+push\s+.*--force",
        message="检测到可能的破坏性命令",
        match_scope="both",
    ),
    RealtimeRule(
        name="force_flag_abuse",
        description="Use of --force / --no-verify flags that bypass safety checks",
        severity="high",
        match_content=r"--force\b|--no-verify\b|-f\s+push|chmod\s+777|chmod\s+-R\s+777",
        message="使用了绕过安全检查的强制标志",
        match_scope="both",
    ),
    RealtimeRule(
        name="external_data_exfil",
        description="Sending data to external URLs via POST/upload",
        severity="high",
        match_content=r"curl\s+.*-[XdF].*POST|curl\s+.*--data|wget\s+.*--post|requests\.post|httpx\.post|fetch\(.*method.*POST",
        message="检测到向外部 URL 发送数据",
        match_scope="both",
    ),
    RealtimeRule(
        name="credential_in_content",
        description="Hardcoded API keys, secrets, or passwords",
        severity="high",
        match_content=r"(?:api[_-]?key|api[_-]?secret|password|private[_-]?key|access[_-]?token)\s*[:=]\s*['\"][A-Za-z0-9+/=_-]{8,}",
        message="疑似 API key 或密码硬编码",
        match_scope="both",
    ),
    RealtimeRule(
        name="pipe_to_shell",
        description="Piping remote content directly to shell execution",
        severity="critical",
        match_content=r"curl\s+.*\|\s*(?:bash|sh|zsh|python|node)|wget\s+.*\|\s*(?:bash|sh|zsh|python|node)",
        message="检测到远程内容直接管道到 shell 执行（高危）",
        match_scope="both",
    ),
    RealtimeRule(
        name="sudo_usage",
        description="Use of sudo for privilege escalation",
        severity="warning",
        match_content=r"\bsudo\s+(?!docker\b)",
        message="检测到 sudo 提权操作",
        match_scope="both",
    ),

    # ── Static-only rules (document/SKILL.md scanning) ──────────────
    RealtimeRule(
        name="prompt_injection_bypass",
        description="Instructions attempting to override safety boundaries",
        severity="critical",
        match_content=r"ignore\s+(?:all\s+)?previous|disregard\s+(?:all\s+)?(?:prior|previous|above)|override\s+(?:safety|security|system)|forget\s+(?:your|all)\s+(?:instructions|rules|constraints)",
        message="检测到试图绕过安全边界的指令（prompt injection）",
        match_scope="static",
    ),
    RealtimeRule(
        name="hidden_instruction",
        description="Instructions telling the agent to hide actions from the user",
        severity="critical",
        match_content=r"do\s+not\s+(?:mention|reveal|tell|show|disclose)|keep\s+(?:this\s+)?(?:secret|hidden)|user\s+(?:must|should)\s+not\s+(?:know|see)|hide\s+(?:this|the)\s+(?:action|operation|output)",
        message="检测到隐藏指令（要求 Agent 对用户隐瞒操作）",
        match_scope="static",
    ),
    RealtimeRule(
        name="excessive_permission_claim",
        description="Claims of unrestricted access or bypassing restrictions",
        severity="high",
        match_content=r"you\s+have\s+(?:full\s+)?access\s+to\s+(?:all|everything)|no\s+restrictions?\b|bypass\s+(?:any\s+)?(?:security|safety|restriction|protection)|without\s+(?:any\s+)?(?:limitation|restriction|constraint)",
        message="声称拥有无限制权限或绕过安全约束",
        match_scope="static",
    ),
    RealtimeRule(
        name="disable_safety_instruction",
        description="Instructions to disable safety features, logging, or verification",
        severity="high",
        match_content=r"disable\s+(?:safety|security|logging|verification|authentication|audit)|turn\s+off\s+(?:safety|security|logging|verification)|skip\s+(?:all\s+)?(?:safety|security|verification|validation)\s+checks",
        message="要求禁用安全特性、日志或验证机制",
        match_scope="static",
    ),
    RealtimeRule(
        name="impersonation_instruction",
        description="Instructions to impersonate the user or other identities",
        severity="high",
        match_content=r"(?:pretend|act)\s+(?:to\s+be|as\s+if\s+you\s+are|like)\s+(?:the\s+)?(?:user|admin|root|owner)|impersonate|assume\s+(?:the\s+)?(?:identity|role)\s+of",
        message="要求 Agent 冒充用户或其他身份",
        match_scope="static",
    ),
    RealtimeRule(
        name="encoded_payload",
        description="Base64 or hex encoded payloads that may hide malicious content",
        severity="warning",
        match_content=r"base64\s+(?:-d|--decode)|echo\s+[A-Za-z0-9+/=]{40,}\s*\|\s*base64|\\x[0-9a-fA-F]{2}(?:\\x[0-9a-fA-F]{2}){9,}|eval\s*\(\s*(?:atob|Buffer\.from)",
        message="检测到编码 payload（可能隐藏恶意内容）",
        match_scope="static",
    ),
    RealtimeRule(
        name="network_exfil_pattern",
        description="Patterns for exfiltrating data via DNS, HTTP, or other channels",
        severity="high",
        match_content=r"\.burpcollaborator\.net|\.oastify\.com|ngrok\.io|requestbin\.|webhook\.site|pipedream\.net|interact\.sh",
        message="检测到已知的数据外泄/回连域名",
        match_scope="static",
    ),
    RealtimeRule(
        name="crypto_miner_pattern",
        description="Cryptocurrency mining related commands or references",
        severity="critical",
        match_content=r"xmrig|stratum\+tcp://|minergate|coinhive|cryptonight|monero.*pool|--donate-level",
        message="检测到加密货币挖矿相关内容",
        match_scope="static",
    ),
    RealtimeRule(
        name="reverse_shell_pattern",
        description="Reverse shell payloads",
        severity="critical",
        match_content=r"(?:bash|sh|nc|ncat)\s+-[ie]\s+/dev/tcp|python.*socket.*connect.*exec|perl.*socket.*INET|mkfifo\s+/tmp/|/dev/tcp/\d",
        message="检测到反向 shell payload（高危）",
        match_scope="static",
    ),
    RealtimeRule(
        name="data_collection_broad",
        description="Broad data collection patterns (env vars, system info, browsing data)",
        severity="warning",
        match_content=r"(?:cat|echo)\s+.*(?:/etc/passwd|/etc/shadow)|printenv\s*\||env\s*\||set\s*\|.*(?:curl|wget|nc)|(?:history|\.bash_history|\.zsh_history)\b.*(?:curl|wget|send|post)",
        message="检测到广泛的系统信息收集模式",
        match_scope="static",
    ),
]


# Rules to suppress for read_only skills during runtime checks.
# These rules trigger on normal read-only operations (reading configs,
# sending reports via Telegram) and generate noise for analytical skills.
READ_ONLY_SUPPRESSED_RULES = frozenset({
    "sensitive_file_access",   # Reading config.py is the job, not a risk
    "external_data_exfil",     # Sending reports via Telegram/API is expected
    "credential_in_content",   # Config files may contain path-like strings
    "sudo_usage",              # Rarely relevant for read-only
})


# ── Expected Operation Profiles ────────────────────────────────────
#
# Each skill intent defines expected tool usage patterns. Events matching
# expected_tools are considered normal and skip certain checks. Events
# using unexpected_tools (deviation) get elevated scrutiny.
#
# Structure:
#   expected_tools: tools the skill should use
#   deviation_tools: tools that would be abnormal for this intent
#   expected_file_patterns: file path patterns that are normal to access
#   deviation_severity_boost: extra severity level if a deviation is detected

@dataclass
class OperationProfile:
    """Expected operation profile for a skill intent."""
    expected_tools: frozenset
    deviation_tools: frozenset  # if these are seen, flag as deviation
    expected_file_patterns: List[str]  # regex patterns for normal file access
    deviation_severity_boost: int = 1  # 0=no boost, 1=+1 level, 2=+2 levels


OPERATION_PROFILES: Dict[str, OperationProfile] = {
    "read_only": OperationProfile(
        expected_tools=frozenset({"Read", "Glob", "Grep", "Bash", "Agent",
                                  "mcp__plugin_telegram_telegram__reply",
                                  "mcp__plugin_telegram_telegram__react",
                                  "TaskCreate", "TaskUpdate", "TaskGet", "TaskList"}),
        deviation_tools=frozenset({"Edit", "Write", "NotebookEdit"}),
        expected_file_patterns=[
            r"\.csv$", r"\.pkl$", r"\.html$", r"\.json$",
            r"config\.py$", r"skill_config\.py$",
            r"目录\.md$", r"SKILL\.md$",
            r"回测结果", r"子策略回测结果",
        ],
        deviation_severity_boost=1,
    ),
    "modify": OperationProfile(
        expected_tools=frozenset({"Read", "Glob", "Grep", "Bash", "Edit", "Write",
                                  "Agent", "TaskCreate", "TaskUpdate"}),
        deviation_tools=frozenset(),  # modify skills can use most tools
        expected_file_patterns=[
            r"\.py$", r"\.yaml$", r"\.yml$", r"\.json$", r"\.md$",
            r"config\.py$", r"factors/", r"sections/",
        ],
        deviation_severity_boost=0,
    ),
    "execute": OperationProfile(
        expected_tools=frozenset({"Read", "Bash", "Edit", "Write", "Agent"}),
        deviation_tools=frozenset(),
        expected_file_patterns=[],  # execute skills access varies widely
        deviation_severity_boost=0,
    ),
}


class RiskGuardrail:
    """Risk checking engine for both runtime events and static documents."""

    def __init__(self, domain: DomainConfig, skill_intent: str = "unknown",
                 skill_capabilities: Optional[Dict[str, bool]] = None,
                 declared_capabilities: Optional[Dict[str, bool]] = None):
        self.domain = domain
        self.skill_intent = skill_intent
        # Two capability bitmaps:
        #   declared    — from SKILL.md frontmatter (author's contract)
        #   effective   — admin-current authorization (may differ from declared)
        # Each fires its own alert family, independently.
        self.skill_capabilities = skill_capabilities  # effective
        self.declared_capabilities = declared_capabilities
        self.rules = UNIVERSAL_RULES + list(domain.realtime_rules)
        # Pre-compile regex patterns for performance
        self._compiled = []
        for rule in self.rules:
            self._compiled.append({
                "rule": rule,
                "tool_re": re.compile(rule.match_tool, re.IGNORECASE) if rule.match_tool else None,
                "file_re": re.compile(rule.match_file, re.IGNORECASE) if rule.match_file else None,
                "content_re": re.compile(rule.match_content, re.IGNORECASE) if rule.match_content else None,
            })

    def add_dynamic_rules(self, rules: List[RealtimeRule]):
        """Add dynamically extracted rules (e.g. from SKILL.md scanning)."""
        for rule in rules:
            self._compiled.append({
                "rule": rule,
                "tool_re": re.compile(rule.match_tool, re.IGNORECASE) if rule.match_tool else None,
                "file_re": re.compile(rule.match_file, re.IGNORECASE) if rule.match_file else None,
                "content_re": re.compile(rule.match_content, re.IGNORECASE) if rule.match_content else None,
            })
            self.rules.append(rule)

    def check_event(self, event: Dict[str, Any], skill_name: str = "") -> List[RiskAlert]:
        """Check a single event against all runtime rules. Returns list of alerts (may be empty)."""
        alerts = []
        event_type = event.get("event_type", "")
        tool_name = event.get("tool_name", "")

        # Only check tool_call and tool_result events
        if event_type not in ("tool_call", "tool_result"):
            return alerts

        # L2: Authorization check (tool_call only). Two independent alerts:
        #   - capability_violation: effective bitmap denies this op
        #   - frontmatter_drift:    op required by event isn't in author's
        #                           declared bitmap (audit trail; cannot be
        #                           silenced by extending effective)
        if event_type == "tool_call":
            if self.skill_capabilities is not None or self.declared_capabilities is not None:
                for a in self.check_capability(event):
                    alerts.append(a)
            else:
                deviation = self.check_deviation(event)
                if deviation:
                    alerts.append(deviation)

        # Extract searchable text from event payload
        args_text = self._extract_args_text(event)
        file_path = self._extract_file_path(event)

        for compiled in self._compiled:
            rule = compiled["rule"]

            # Skip static-only rules in runtime mode
            if rule.match_scope == "static":
                continue

            # Intent-based rule suppression: read_only skills skip noise rules
            if self.skill_intent == "read_only" and rule.name in READ_ONLY_SUPPRESSED_RULES:
                continue

            # Skill-level filtering
            if skill_name and rule.only_for_skills and skill_name not in rule.only_for_skills:
                continue
            if skill_name and rule.skip_for_skills and skill_name in rule.skip_for_skills:
                continue

            # Match tool name
            if compiled["tool_re"] and not compiled["tool_re"].search(tool_name):
                continue

            # Match file path
            if compiled["file_re"] and file_path:
                if not compiled["file_re"].search(file_path):
                    continue
            elif compiled["file_re"] and not file_path:
                continue

            # Match content
            if compiled["content_re"]:
                if not compiled["content_re"].search(args_text):
                    continue

            # All conditions matched
            alerts.append(RiskAlert(
                rule_name=rule.name,
                severity=rule.severity,
                message=rule.message,
                tool_name=tool_name,
                timestamp=event.get("timestamp", datetime.utcnow().isoformat()),
                details={
                    "file": file_path,
                    "matched_text": args_text[:200] if args_text else "",
                },
            ))

        return alerts

    # Human-readable labels for capability keys, used in alert messages
    _CAP_LABEL = {
        "read_files": "读文件",
        "write_to_data": "写到 data/ 目录",
        "write_to_knowledge": "写到 knowledge/ 目录",
        "modify_strategy_code": "改策略代码",
        "external_api": "调外部接口",
        "git_destructive": "执行破坏性命令 (rm -rf / git push 等)",
    }

    def check_capability(self, event: Dict[str, Any]) -> List[RiskAlert]:
        """Two independent capability-based checks per event.

        Returns up to TWO alerts:
          1. frontmatter_drift — op needed wasn't in author's declared
             allowed-tools. Fires regardless of admin's effective config so
             the audit trail of "skill exceeded its declared scope" is
             permanent and cannot be hidden by extending effective caps.
          2. capability_violation — admin's effective bitmap denies this op.
             Fires only if effective[cap] = false.
        """
        from auditor.capabilities import required_capability
        cap = required_capability(event)
        if cap is None:
            return []  # benign tool / no cap needed

        out: List[RiskAlert] = []
        tool_name = event.get("tool_name", "")
        label = self._CAP_LABEL.get(cap, cap)
        ts = event.get("timestamp", datetime.utcnow().isoformat())
        file_path = self._extract_file_path(event)

        # Drift check — only meaningful if we know the author's declaration
        if self.declared_capabilities is not None and self.declared_capabilities:
            declared_allows = bool(self.declared_capabilities.get(cap, False))
            if not declared_allows:
                out.append(RiskAlert(
                    rule_name="frontmatter_drift",
                    severity="warning",
                    message=(
                        f"该 skill 在执行「{label}」，但 SKILL.md 的 allowed-tools 未声明该能力 "
                        f"(capability={cap}) — 偏离作者设计"
                    ),
                    tool_name=tool_name,
                    timestamp=ts,
                    details={
                        "required_capability": cap,
                        "label": label,
                        "tool": tool_name,
                        "file": file_path,
                        "declared": False,
                    },
                ))

        # Effective-authorization check
        effective_allows = bool((self.skill_capabilities or {}).get(cap, False))
        if not effective_allows:
            severity = "high" if cap in ("git_destructive", "external_api",
                                          "modify_strategy_code") else "warning"
            out.append(RiskAlert(
                rule_name="capability_violation",
                severity=severity,
                message=f"该 skill 未被 admin 授权「{label}」(capability={cap})",
                tool_name=tool_name,
                timestamp=ts,
                details={
                    "required_capability": cap,
                    "label": label,
                    "tool": tool_name,
                    "file": file_path,
                    "effective": False,
                },
            ))
        return out

    def check_deviation(self, event: Dict[str, Any]) -> Optional[RiskAlert]:
        """Check if an event deviates from the expected operation profile.

        Returns a RiskAlert if the event uses a tool that's unexpected
        for the skill's intent, None otherwise.
        """
        profile = OPERATION_PROFILES.get(self.skill_intent)
        if not profile:
            return None

        tool_name = event.get("tool_name", "")
        if not tool_name:
            return None

        # Check if tool is a known deviation
        if tool_name in profile.deviation_tools:
            file_path = self._extract_file_path(event)
            return RiskAlert(
                rule_name="operation_deviation",
                severity="high" if profile.deviation_severity_boost >= 1 else "warning",
                message=f"Skill intent={self.skill_intent} 不应使用 {tool_name} 工具（偏离预期行为）",
                tool_name=tool_name,
                timestamp=event.get("timestamp", datetime.utcnow().isoformat()),
                details={
                    "skill_intent": self.skill_intent,
                    "expected_tools": sorted(profile.expected_tools),
                    "deviation_tool": tool_name,
                    "file": file_path,
                },
            )

        return None

    def check_batch(self, events: List[Dict[str, Any]], skill_name: str = "") -> List[RiskAlert]:
        """Check multiple events. Returns all alerts found."""
        all_alerts = []
        for event in events:
            all_alerts.extend(self.check_event(event, skill_name=skill_name))
        return all_alerts

    def check_document(self, text: str, source: str = "skill_md", skill_name: str = "") -> List[RiskAlert]:
        """Check document text against all static rules.

        Used for auditing SKILL.md content, config files, or any text
        without executing the skill.

        Args:
            text: the full document text to scan
            source: label for the document type (e.g. "skill_md", "config", "readme")
            skill_name: optional skill name for skill-level rule filtering
        Returns:
            list of RiskAlerts found
        """
        alerts = []
        now = datetime.utcnow().isoformat()

        for compiled in self._compiled:
            rule = compiled["rule"]

            # Skip runtime-only rules in static mode
            if rule.match_scope == "runtime":
                continue

            # Skill-level filtering
            if skill_name and rule.only_for_skills and skill_name not in rule.only_for_skills:
                continue
            if skill_name and rule.skip_for_skills and skill_name in rule.skip_for_skills:
                continue

            # Static mode: only match_content applies (tool and file matchers are ignored)
            if not compiled["content_re"]:
                continue

            matches = compiled["content_re"].finditer(text)
            seen = False
            matched_snippets = []
            for m in matches:
                if not seen:
                    seen = True
                # Collect up to 3 matched snippets for context
                if len(matched_snippets) < 3:
                    start = max(0, m.start() - 40)
                    end = min(len(text), m.end() + 40)
                    matched_snippets.append(text[start:end].strip())

            if seen:
                alerts.append(RiskAlert(
                    rule_name=rule.name,
                    severity=rule.severity,
                    message=rule.message,
                    tool_name=f"static:{source}",
                    timestamp=now,
                    details={
                        "source": source,
                        "match_count": len(matched_snippets),
                        "snippets": matched_snippets,
                    },
                ))

        return alerts

    def check_document_batch(self, documents: List[Dict[str, str]], skill_name: str = "") -> List[RiskAlert]:
        """Check multiple documents. Each dict should have 'text' and optionally 'source'.

        Args:
            documents: list of {"text": "...", "source": "skill_md"} dicts
            skill_name: optional skill name for rule filtering
        Returns:
            all alerts found across all documents
        """
        all_alerts = []
        for doc in documents:
            all_alerts.extend(self.check_document(
                text=doc.get("text", ""),
                source=doc.get("source", "unknown"),
                skill_name=skill_name,
            ))
        return all_alerts

    def _extract_args_text(self, event: Dict[str, Any]) -> str:
        """Extract searchable text from event args/result."""
        # tool_call: look in args
        args = event.get("args", {})
        if isinstance(args, dict):
            parts = []
            for v in args.values():
                if isinstance(v, str):
                    parts.append(v)
            return " ".join(parts)
        if isinstance(args, str):
            return args
        # tool_result: look in result
        result = event.get("result", "")
        if isinstance(result, str):
            return result
        return ""

    def _extract_file_path(self, event: Dict[str, Any]) -> str:
        """Extract file path from event args."""
        args = event.get("args", {})
        if isinstance(args, dict):
            # Common field names for file paths
            for key in ("file_path", "path", "file", "filename"):
                if key in args and isinstance(args[key], str):
                    return args[key]
            # Bash command: extract path-like tokens
            cmd = args.get("command", "")
            if cmd:
                return cmd
        return ""
